oc login 10.1.2.2:8443 -u openshift-dev -p devel
oc login 10.2.2.2:8443 -u openshift-dev -p devel
oc login openshift.adb:8443 -u openshift-dev -p devel
oc login 192.168.99.100:8443 -u developer -p developer
oc login https://api.preview.openshift.com --token=[OPENSHIFT_ONLINE_TOKEN] # https://console.preview.openshift.com/console/command-line

----

mvn package -DskipTests=true

oc new-project hello-world --display-name="Hello World Greeting Service on OpenShift" --description="Learning project about building and deploying SpringBoot applications using OpenShift Client Tool."

oc new-build --binary --name=hello-world --labels=app=hello-world
oc start-build hello-world --from-dir=. --follow
oc new-app hello-world --labels=app=hello-world
oc set probe dc/hello-world --readiness --get-url=http://:10000/ws/rest/services
oc set probe dc/hello-world --liveness  --get-url=http://:10000/ws/rest/services
oc logs --follow dc/hello-world
oc expose svc/hello-world --path=/ws/rest/services
