#!/usr/bin/env groovy

node {

    stage name: 'DEV', concurrency: 1
        git url: 'https://github.com/straider/challenges.git',
            branch: 'master',
            credentialsId: 'github-straider'
            
        sh "cd '/var/lib/jenkins/jobs/SpringBoot CXF Greeting Service/workspace/challenges/LearningPath/2017/EnterpriseContainerisation/OpenShift/ContinuousIntegrationDeliveryPipeline/SpringBootGreetingService/'"
            
        echo 'Successfully staged DEV environment'

    stage name: 'TST', concurrency: 1
        echo 'Successfully staged TST environment'

    stage name: 'STG', concurrency: 1
        echo 'Successfully staged STG environment'

    stage name: 'PRD', concurrency: 1
        echo 'Successfully staged PRD environment'

}
