curl http://localhost:10000

curl http://localhost:10000/people

curl -i -X POST -H "Content-Type:application/json" -d "{  \"firstName\" : \"Frodo\",  \"lastName\" : \"Baggins\" }" http://localhost:10000/people

curl http://localhost:10000/people/search

curl http://localhost:10000/people/search/findByLastName?name=Baggins

curl -X PUT -H "Content-Type:application/json" -d "{ \"firstName\": \"Bilbo\", \"lastName\": \"Baggins\" }" http://localhost:10000/people/[ID]
curl http://localhost:10000/people/[ID]
curl -X PATCH -H "Content-Type:application/json" -d "{ \"firstName\": \"Bilbo Jr.\" }" http://localhost:10000/people/[ID]
curl http://localhost:10000/people/[ID]

curl -X DELETE http://localhost:10000/people/[ID]
curl http://localhost:10000/people
curl http://localhost:10000/people/search/findByLastName?name=Baggins
