apiVersion: v1
kind: Service
metadata:
  labels:
    app: [APPLICATION_NAME]
  name: [SERVICE_ARTIFACT_ID]
spec:
  selector:
    app: [SERVICE_ARTIFACT_ID]
  ports:
    - port: [SERVICE_DEFAULT_PORT]
      protocol: TCP
      targetPort: [SERVICE_DEFAULT_PORT]
  sessionAffinity: ClientIP
  type: ClusterIP
